# Site settings
title: Matt's Frontend Training
author: Matthew Shaw
email:
description: Matt's frontend self-training course
baseurl: "/frontend-training/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

gems:
  - jekyll-sitemap
  - jemoji

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
highlighter: pygments
